package com.trucktrans.entity.dto;

// Generated 12 Oct, 2015 11:47:03 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtAppTrackInfo generated by hbm2java
 */
@Entity
@Table(name = "tt_app_track_info", catalog = "trucksys")
public class AppTrackInfoDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private long trackId;
	private UserDTO userDTO;
	private String activity;
	private Date trackedDate;
	private String activityDescription;

	public AppTrackInfoDTO() {
	}

	public AppTrackInfoDTO(long trackId, UserDTO ttUser, String activity, Date trackedDate) {
		this.trackId = trackId;
		this.userDTO = ttUser;
		this.activity = activity;
		this.trackedDate = trackedDate;
	}

	public AppTrackInfoDTO(long trackId, UserDTO ttUser, String activity, Date trackedDate, String activityDescription) {
		this.trackId = trackId;
		this.userDTO = ttUser;
		this.activity = activity;
		this.trackedDate = trackedDate;
		this.activityDescription = activityDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TRACK_ID", unique = true, nullable = false)
	public long getTrackId() {
		return this.trackId;
	}

	public void setTrackId(long trackId) {
		this.trackId = trackId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public UserDTO getUserDTO() {
		return this.userDTO;
	}

	public void setUserDTO(UserDTO userDTO) {
		this.userDTO = userDTO;
	}

	@Column(name = "ACTIVITY", nullable = false, length = 45)
	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRACKED_DATE", nullable = false, length = 19)
	public Date getTrackedDate() {
		return this.trackedDate;
	}

	public void setTrackedDate(Date trackedDate) {
		this.trackedDate = trackedDate;
	}

	@Column(name = "ACTIVITY_DESCRIPTION", length = 500)
	public String getActivityDescription() {
		return this.activityDescription;
	}

	public void setActivityDescription(String activityDescription) {
		this.activityDescription = activityDescription;
	}

}
