package com.trucktrans.entity.dto;

// Generated 12 Oct, 2015 11:47:03 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RefReviewDTO generated by hbm2java
 */
@Entity
@Table(name = "tt_ref_review", catalog = "trucksys")
public class RefReviewDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private long reviewId;
	private String city;
	private Long dateCreated;
	private String review;
	private long inputTimestamp;
	private Double rating;
	private String state;
	private String userName;
	private Long companyId;

	public RefReviewDTO() {
	}

	public RefReviewDTO(long reviewId, long inputTimestamp) {
		this.reviewId = reviewId;
		this.inputTimestamp = inputTimestamp;
	}

	public RefReviewDTO(long reviewId, String city, Long dateCreated, String review, long inputTimestamp, Double rating,
			String state, String userName, Long companyId) {
		this.reviewId = reviewId;
		this.city = city;
		this.dateCreated = dateCreated;
		this.review = review;
		this.inputTimestamp = inputTimestamp;
		this.rating = rating;
		this.state = state;
		this.userName = userName;
		this.companyId = companyId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "REVIEW_ID", unique = true, nullable = false)
	public long getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(long reviewId) {
		this.reviewId = reviewId;
	}

	@Column(name = "CITY", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "DATE_CREATED")
	public Long getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Long dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "REVIEW")
	public String getReview() {
		return this.review;
	}

	public void setReview(String review) {
		this.review = review;
	}

	@Column(name = "INPUT_TIMESTAMP", nullable = false)
	public long getInputTimestamp() {
		return this.inputTimestamp;
	}

	public void setInputTimestamp(long inputTimestamp) {
		this.inputTimestamp = inputTimestamp;
	}

	@Column(name = "RATING", precision = 22, scale = 0)
	public Double getRating() {
		return this.rating;
	}

	public void setRating(Double rating) {
		this.rating = rating;
	}

	@Column(name = "STATE", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "USER_NAME", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "COMPANY_ID")
	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

}
