package com.trucktrans.entity.dto;

// Generated 12 Oct, 2015 11:47:03 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ServiceTableDTO generated by hbm2java
 */
@Entity
@Table(name = "tt_service_table", catalog = "trucksys")
public class ServiceTableDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private short serviceId;
	private String serviceDescription;
	private String weightDescription;
	private Set<TruckServiceTypeDTO> truckServiceTypesDTOs = new HashSet<TruckServiceTypeDTO>(0);

	public ServiceTableDTO() {
	}

	public ServiceTableDTO(short serviceId) {
		this.serviceId = serviceId;
	}

	public ServiceTableDTO(short serviceId, String serviceDescription, String weightDescription, Set<TruckServiceTypeDTO> truckServiceTypesDTOs) {
		this.serviceId = serviceId;
		this.serviceDescription = serviceDescription;
		this.weightDescription = weightDescription;
		this.truckServiceTypesDTOs = truckServiceTypesDTOs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SERVICE_ID", unique = true, nullable = false)
	public short getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(short serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "SERVICE_DESCRIPTION", length = 45)
	public String getServiceDescription() {
		return this.serviceDescription;
	}

	public void setServiceDescription(String serviceDescription) {
		this.serviceDescription = serviceDescription;
	}

	@Column(name = "WEIGHT_DESCRIPTION", length = 45)
	public String getWeightDescription() {
		return this.weightDescription;
	}

	public void setWeightDescription(String weightDescription) {
		this.weightDescription = weightDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceTableDTO")
	public Set<TruckServiceTypeDTO> getTruckServiceTypesDTOs() {
		return this.truckServiceTypesDTOs;
	}

	public void setTruckServiceTypesDTOs(Set<TruckServiceTypeDTO> truckServiceTypeDTOs) {
		this.truckServiceTypesDTOs = truckServiceTypeDTOs;
	}

}
