package com.trucktrans.entity.dto;

// Generated 12 Oct, 2015 11:47:03 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SourceDestinationInfoDTO generated by hbm2java
 */
@Entity
@Table(name = "tt_source_destination_info", catalog = "trucksys")
public class SourceDestinationInfoDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int placeId;
	private StateInfoDTO stateInfoDTO;
	private String name;
	private String placeDesc;
	private int pincode;
	private Boolean enabled;

	public SourceDestinationInfoDTO() {
	}

	public SourceDestinationInfoDTO(int placeId, StateInfoDTO stateInfoDTO, String name, int pincode) {
		this.placeId = placeId;
		this.stateInfoDTO = stateInfoDTO;
		this.name = name;
		this.pincode = pincode;
	}

	public SourceDestinationInfoDTO(int placeId, StateInfoDTO ttStateInfo, String name, String placeDesc, int pincode,
			Boolean enabled) {
		this.placeId = placeId;
		this.stateInfoDTO = ttStateInfo;
		this.name = name;
		this.placeDesc = placeDesc;
		this.pincode = pincode;
		this.enabled = enabled;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PLACE_ID", unique = true, nullable = false)
	public int getPlaceId() {
		return this.placeId;
	}

	public void setPlaceId(int placeId) {
		this.placeId = placeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATE_ID", nullable = false)
	public StateInfoDTO getStateInfoDTO() {
		return this.stateInfoDTO;
	}

	public void setStateInfoDTO(StateInfoDTO stateInfoDTO) {
		this.stateInfoDTO = stateInfoDTO;
	}

	@Column(name = "NAME", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PLACE_DESC", length = 45)
	public String getPlaceDesc() {
		return this.placeDesc;
	}

	public void setPlaceDesc(String placeDesc) {
		this.placeDesc = placeDesc;
	}

	@Column(name = "PINCODE", nullable = false)
	public int getPincode() {
		return this.pincode;
	}

	public void setPincode(int pincode) {
		this.pincode = pincode;
	}

	@Column(name = "ENABLED")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

}
