package com.trucktrans.entity.dto;

// Generated 12 Oct, 2015 11:47:03 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StateInfoDTO generated by hbm2java
 */
@Entity
@Table(name = "tt_state_info", catalog = "trucksys")
public class StateInfoDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int stateId;
	private int pincode;
	private String name;
	private String stateDesc;
	private Boolean enabled;
	private Set<SourceDestinationInfoDTO> sourceDestinationInfoDTOs = new HashSet<SourceDestinationInfoDTO>(0);

	public StateInfoDTO() {
	}

	public StateInfoDTO(int stateId, int pincode, String name) {
		this.stateId = stateId;
		this.pincode = pincode;
		this.name = name;
	}

	public StateInfoDTO(int stateId, int pincode, String name, String stateDesc, Boolean enabled,
			Set<SourceDestinationInfoDTO> sourceDestinationInfoDTOs) {
		this.stateId = stateId;
		this.pincode = pincode;
		this.name = name;
		this.stateDesc = stateDesc;
		this.enabled = enabled;
		this.sourceDestinationInfoDTOs = sourceDestinationInfoDTOs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "STATE_ID", unique = true, nullable = false)
	public int getStateId() {
		return this.stateId;
	}

	public void setStateId(int stateId) {
		this.stateId = stateId;
	}

	@Column(name = "PINCODE", nullable = false)
	public int getPincode() {
		return this.pincode;
	}

	public void setPincode(int pincode) {
		this.pincode = pincode;
	}

	@Column(name = "NAME", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "STATE_DESC", length = 45)
	public String getStateDesc() {
		return this.stateDesc;
	}

	public void setStateDesc(String stateDesc) {
		this.stateDesc = stateDesc;
	}

	@Column(name = "ENABLED")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stateInfoDTO")
	public Set<SourceDestinationInfoDTO> getSourceDestinationInfoDTOs() {
		return this.sourceDestinationInfoDTOs;
	}

	public void setSourceDestinationInfoDTOs(Set<SourceDestinationInfoDTO> sourceDestinationInfoDTOs) {
		this.sourceDestinationInfoDTOs = sourceDestinationInfoDTOs;
	}

}
