package com.trucktrans.entity.dto;

// Generated 12 Oct, 2015 11:47:03 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TransComQuotesDTO generated by hbm2java
 */
@Entity
@Table(name = "tt_trans_com_quotes", catalog = "trucksys")
public class TransComQuotesDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int quoteId;
	private String companyName;
	private String truckType;
	private int priceEstimates;
	private Long maxTime;
	private Long minTime;
	private String remarks;
	private UserBookingReqDTO userBookingReqDTO;	
	
	
	
	public TransComQuotesDTO() {
	}

	public TransComQuotesDTO(int quoteId, UserBookingReqDTO userBookingReqDTO, String companyName) {
		this.quoteId = quoteId;
		this.userBookingReqDTO = userBookingReqDTO;
		this.companyName = companyName;
	}

	public TransComQuotesDTO(int quoteId, UserBookingReqDTO userBookingReqDTO, String companyName, String truckType,
			int priceEstimates, Long maxTime, Long minTime, String remarks) {
		this.quoteId = quoteId;
		this.userBookingReqDTO = userBookingReqDTO;
		this.companyName = companyName;
		this.truckType = truckType;
		this.priceEstimates = priceEstimates;
		this.maxTime = maxTime;
		this.minTime = minTime;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QUOTE_ID", unique = true, nullable = false)
	public int getQuoteId() {
		return this.quoteId;
	}

	public void setQuoteId(int quoteId) {
		this.quoteId = quoteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BOOKING_ID", nullable = false)
	public UserBookingReqDTO getUserBookingReqDTO() {
		return this.userBookingReqDTO;
	}

	public void setUserBookingReqDTO(UserBookingReqDTO userBookingReqDTO) {
		this.userBookingReqDTO = userBookingReqDTO;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANY_ID", nullable = false)
	public TransComDetailsDTO getTransComDetailsDTO() {
		return transComDetailsDTO;
	}
	public void setTransComDetailsDTO(TransComDetailsDTO transComDetailsDTO) {
		this.transComDetailsDTO = transComDetailsDTO;
	}*/

	
	
	@Column(name = "COMPANY_NAME", nullable = false, length = 100)
	public String getCompanyName() {
		return this.companyName;
	}
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "TRUCK_TYPE", length = 45)
	public String getTruckType() {
		return this.truckType;
	}
	public void setTruckType(String truckType) {
		this.truckType = truckType;
	}

	@Column(name = "PRICE_ESTIMATES", length = 45)
	public Integer getPriceEstimates() {
		return this.priceEstimates;
	}
	public void setPriceEstimates(Integer priceEstimates) {
		this.priceEstimates = priceEstimates;
	}

	@Column(name = "MAX_TIME", length = 45)
	public Long getMaxTime() {
		return this.maxTime;
	}
	public void setMaxTime(Long maxTime) {
		this.maxTime = maxTime;
	}

	@Column(name = "MIN_TIME", length = 45)
	public Long getMinTime() {
		return minTime;
	}
	public void setMinTime(Long minTime) {
		this.minTime = minTime;
	}

	@Column(name = "REMARKS")
	public String getRemarks() {
		return this.remarks;
	}
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
