package com.trucktrans.entity.dto;

// Generated 12 Oct, 2015 11:47:03 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransComDetailsDTO generated by hbm2java
 */
@Entity
@Table(name = "tt_trans_com_details", catalog = "trucksys")
public class TransComDetailsDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	
	private int companyId;
	private UserDTO user;
	private String name;
	private String companyDesc;
	private Short truckStrength;
	private Set<TruckServiceTypeDTO> truckServiceTypeDTOs = new HashSet<TruckServiceTypeDTO>(0);
	private Set<TransComQuotesDTO> transComQuotesDTOs = new HashSet<TransComQuotesDTO>(0);
	
	
	
	
	public TransComDetailsDTO() {
	}

	public TransComDetailsDTO(int companyId) {
		this.companyId = companyId;
	}

	public TransComDetailsDTO(int companyId, UserDTO user, String name, String companyDesc, Short truckStrength,
			Set<TruckServiceTypeDTO> truckServiceTypeDTOs) {
		this.companyId = companyId;
		this.user = user;
		this.name = name;
		this.companyDesc = companyDesc;
		this.truckStrength = truckStrength;
		this.truckServiceTypeDTOs = truckServiceTypeDTOs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "COMPANY_ID", unique = true, nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public UserDTO getUser() {
		return this.user;
	}

	public void setUser(UserDTO user) {
		this.user = user;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "COMPANY_DESC")
	public String getCompanyDesc() {
		return this.companyDesc;
	}

	public void setCompanyDesc(String companyDesc) {
		this.companyDesc = companyDesc;
	}

	@Column(name = "TRUCK_STRENGTH")
	public Short getTruckStrength() {
		return this.truckStrength;
	}

	public void setTruckStrength(Short truckStrength) {
		this.truckStrength = truckStrength;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transComDetailsDTO")
	public Set<TruckServiceTypeDTO> getTruckServiceTypeDTOs() {
		return this.truckServiceTypeDTOs;
	}

	public void setTruckServiceTypeDTOs(Set<TruckServiceTypeDTO> truckServiceTypeDTOs) {
		this.truckServiceTypeDTOs = truckServiceTypeDTOs;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transComDetailsDTO")
	public Set<TransComQuotesDTO> getTransComQuotesDTOs() {
		return transComQuotesDTOs;
	}

	public void setTransComQuotesDTOs(Set<TransComQuotesDTO> transComQuotesDTOs) {
		this.transComQuotesDTOs = transComQuotesDTOs;
	}

	

}
