package com.trucktrans.entity.dto;

// Generated 12 Oct, 2015 11:47:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TruckServiceTypeId generated by hbm2java
 */
@Embeddable
public class TruckServiceTypeId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int companyId;
	private Short serviceId;

	public TruckServiceTypeId() {
	}

	public TruckServiceTypeId(int companyId) {
		this.companyId = companyId;
	}

	public TruckServiceTypeId(int companyId, Short serviceId) {
		this.companyId = companyId;
		this.serviceId = serviceId;
	}

	@Column(name = "COMPANY_ID", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Column(name = "SERVICE_ID")
	public Short getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Short serviceId) {
		this.serviceId = serviceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TruckServiceTypeId))
			return false;
		TruckServiceTypeId castOther = (TruckServiceTypeId) other;

		return (this.getCompanyId() == castOther.getCompanyId())
				&& ((this.getServiceId() == castOther.getServiceId()) || (this.getServiceId() != null
						&& castOther.getServiceId() != null && this.getServiceId().equals(castOther.getServiceId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCompanyId();
		result = 37 * result + (getServiceId() == null ? 0 : this.getServiceId().hashCode());
		return result;
	}

}
