package com.trucktrans.entity.dto;

// Generated 12 Oct, 2015 11:47:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TruckServiceTypeDTO generated by hbm2java
 */
@Entity
@Table(name = "tt_truck_service_type", catalog = "trucksys")
public class TruckServiceTypeDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private TruckServiceTypeId id;
	private TransComDetailsDTO transComDetailsDTO;
	private ServiceTableDTO serviceTableDTO;

	public TruckServiceTypeDTO() {
	}

	public TruckServiceTypeDTO(TruckServiceTypeId id, TransComDetailsDTO transComDetailsDTO) {
		this.id = id;
		this.transComDetailsDTO = transComDetailsDTO;
	}

	public TruckServiceTypeDTO(TruckServiceTypeId id, TransComDetailsDTO ttTransComDetails,
			ServiceTableDTO serviceTableDTO) {
		this.id = id;
		this.transComDetailsDTO = ttTransComDetails;
		this.serviceTableDTO = serviceTableDTO;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "companyId", column = @Column(name = "COMPANY_ID", nullable = false)),
			@AttributeOverride(name = "serviceId", column = @Column(name = "SERVICE_ID")) })
	public TruckServiceTypeId getId() {
		return this.id;
	}

	public void setId(TruckServiceTypeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANY_ID", nullable = false, insertable = false, updatable = false)
	public TransComDetailsDTO getTransComDetailsDTO() {
		return this.transComDetailsDTO;
	}

	public void setTransComDetailsDTO(TransComDetailsDTO transComDetailsDTO) {
		this.transComDetailsDTO = transComDetailsDTO;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICE_ID", insertable = false, updatable = false)
	public ServiceTableDTO getServiceTableDTO() {
		return this.serviceTableDTO;
	}

	public void setServiceTableDTO(ServiceTableDTO serviceTableDTO) {
		this.serviceTableDTO = serviceTableDTO;
	}

}
