package com.trucktrans.entity.dto;

// Generated 12 Oct, 2015 11:47:03 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtUserBookingReq generated by hbm2java
 */
@Entity
@Table(name = "tt_user_booking_req", catalog = "trucksys")
public class UserBookingReqDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int bookingId;
	private UserDTO user;
	private int sourceStateId;
	private int sourcePlaceId;
	private String sourceAddress;
	private int destinationStateId;
	private int destinationPlaceId;
	private String destinationAddress;
	

	private Date dateOfRequest;
	private String truckType;
	private Boolean partialLoadFlag;
	private String remarks;
	private Set<TransComQuotesDTO> transComQuotesDTOs = new HashSet<TransComQuotesDTO>(0);

	public UserBookingReqDTO() {
	}

	public UserBookingReqDTO(int bookingId, UserDTO user, int sourceStateId, int sourcePlaceId, int destinationStateId,
			int destinationPlaceId) {
		this.bookingId = bookingId;
		this.user = user;
		this.sourceStateId = sourceStateId;
		this.sourcePlaceId = sourcePlaceId;
		this.destinationStateId = destinationStateId;
		this.destinationPlaceId = destinationPlaceId;
	}

	public UserBookingReqDTO(int bookingId, UserDTO user, int sourceStateId, int sourcePlaceId, int destinationStateId,
			int destinationPlaceId, Date dateOfRequest, String truckType, Boolean partialLoadFlag, String remarks,
			Set<TransComQuotesDTO> transComQuotesDTOs, String sourceAddress, String destinationAddress) {
		this.bookingId = bookingId;
		this.user = user;
		this.sourceStateId = sourceStateId;
		this.sourcePlaceId = sourcePlaceId;
		this.destinationStateId = destinationStateId;
		this.destinationPlaceId = destinationPlaceId;
		this.dateOfRequest = dateOfRequest;
		this.truckType = truckType;
		this.partialLoadFlag = partialLoadFlag;
		this.remarks = remarks;
		this.transComQuotesDTOs = transComQuotesDTOs;
		this.sourceAddress=sourceAddress;
		this.destinationAddress=destinationAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BOOKING_ID", unique = true, nullable = false)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public UserDTO getUser() {
		return this.user;
	}

	public void setUser(UserDTO user) {
		this.user = user;
	}

	@Column(name = "SOURCE_STATE_ID", nullable = false)
	public int getSourceStateId() {
		return this.sourceStateId;
	}

	public void setSourceStateId(int sourceStateId) {
		this.sourceStateId = sourceStateId;
	}

	@Column(name = "SOURCE_PLACE_ID", nullable = false)
	public int getSourcePlaceId() {
		return this.sourcePlaceId;
	}

	public void setSourcePlaceId(int sourcePlaceId) {
		this.sourcePlaceId = sourcePlaceId;
	}

	@Column(name = "SOURCE_ADDRESS", nullable = false)
	public String getSourceAddress() {
		return sourceAddress;
	}

	public void setSourceAddress(String sourceAddress) {
		this.sourceAddress = sourceAddress;
	}
	
	@Column(name = "DESTINATION_STATE_ID", nullable = false)
	public int getDestinationStateId() {
		return this.destinationStateId;
	}

	public void setDestinationStateId(int destinationStateId) {
		this.destinationStateId = destinationStateId;
	}

	@Column(name = "DESTINATION_PLACE_ID", nullable = false)
	public int getDestinationPlaceId() {
		return this.destinationPlaceId;
	}

	public void setDestinationPlaceId(int destinationPlaceId) {
		this.destinationPlaceId = destinationPlaceId;
	}

	@Column(name = "DESTINATION_ADDRESS", nullable = false)
	public String getDestinationAddress() {
		return destinationAddress;
	}

	public void setDestinationAddress(String destinationAddress) {
		this.destinationAddress = destinationAddress;
	}
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_REQUEST", length = 19)
	public Date getDateOfRequest() {
		return this.dateOfRequest;
	}

	public void setDateOfRequest(Date dateOfRequest) {
		this.dateOfRequest = dateOfRequest;
	}

	@Column(name = "TRUCK_TYPE", length = 45)
	public String getTruckType() {
		return this.truckType;
	}

	public void setTruckType(String truckType) {
		this.truckType = truckType;
	}

	@Column(name = "PARTIAL_LOAD_FLAG")
	public Boolean getPartialLoadFlag() {
		return this.partialLoadFlag;
	}

	public void setPartialLoadFlag(Boolean partialLoadFlag) {
		this.partialLoadFlag = partialLoadFlag;
	}

	@Column(name = "REMARKS")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userBookingReqDTO")
	public Set<TransComQuotesDTO> getTransComQuotesDTOs() {
		return this.transComQuotesDTOs;
	}

	public void setTransComQuotesDTOs(Set<TransComQuotesDTO> transComQuotesDTOs) {
		this.transComQuotesDTOs = transComQuotesDTOs;
	}

}
