package com.trucktrans.entity.dto;

// Generated 12 Oct, 2015 11:47:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserRolesId generated by hbm2java
 */
@Embeddable
public class UserRolesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Long roleId;
	private long userId;

	public UserRolesId() {
	}

	public UserRolesId(Long roleId, long userId) {
		this.roleId = roleId;
		this.userId = userId;
	}

	@Column(name = "ROLE_ID", nullable = false)
	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "USER_ID", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRolesId))
			return false;
		UserRolesId castOther = (UserRolesId) other;

		return (this.getRoleId() == castOther.getRoleId()) && (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		Long result = 17L;

		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getUserId();
		return result.intValue();
	}

	@Override
	public String toString() {
		return "UserRolesId [roleId=" + roleId + ", userId=" + userId + "]";
	}
	
	

}
