package com.trucktrans.entity.dto;

// Generated 12 Oct, 2015 11:47:03 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * TtUserBookingReq generated by hbm2java
 */
@Entity
@Table(name = "tt_user_booking_req", catalog = "trucksys")
public class UserBookingReqDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int bookingId;
	private UserDTO user;
	private StateInfoDTO sourceState;
	private String sourcePlace;
	private String sourceAddress;
	private StateInfoDTO destinationState;
	private String destinationPlace;
	private String destinationAddress;
	

	private Date dateOfRequest;
	private String truckType;
	private Boolean partialLoadFlag;
	private String remarks;
	private Set<TransComQuotesDTO> transComQuotesDTOs = new HashSet<TransComQuotesDTO>(0);

	public UserBookingReqDTO() {
	}

	public UserBookingReqDTO(int bookingId, UserDTO user, StateInfoDTO sourceStateId, String sourcePlace, StateInfoDTO destinationStateId,
			String destinationPlace) {
		this.bookingId = bookingId;
		this.user = user;
		this.sourceState = sourceStateId;
		this.sourcePlace = sourcePlace;
		this.destinationState = destinationStateId;
		this.destinationPlace = destinationPlace;
	}

	public UserBookingReqDTO(int bookingId, UserDTO user, StateInfoDTO sourceState, String sourcePlace, StateInfoDTO destinationState,
			String destinationPlace, Date dateOfRequest, String truckType, Boolean partialLoadFlag, String remarks,
			Set<TransComQuotesDTO> transComQuotesDTOs, String sourceAddress, String destinationAddress) {
		this.bookingId = bookingId;
		this.user = user;
		this.sourceState = sourceState;
		this.sourcePlace = sourcePlace;
		this.destinationState = destinationState;
		this.destinationPlace = destinationPlace;
		this.dateOfRequest = dateOfRequest;
		this.truckType = truckType;
		this.partialLoadFlag = partialLoadFlag;
		this.remarks = remarks;
		this.transComQuotesDTOs = transComQuotesDTOs;
		this.sourceAddress=sourceAddress;
		this.destinationAddress=destinationAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BOOKING_ID", unique = true, nullable = false)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USER_ID", nullable = false)
	@JsonBackReference
	public UserDTO getUser() {
		return this.user;
	}

	public void setUser(UserDTO user) {
		this.user = user;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SOURCE_STATE", nullable = false)
	@JsonBackReference
	public StateInfoDTO getSourceState() {
		return this.sourceState;
	}

	public void setSourceState(StateInfoDTO sourceStateId) {
		this.sourceState = sourceStateId;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DESTINATION_STATE", nullable = false)
	@JsonBackReference
	public StateInfoDTO getDestinationState() {
		return this.destinationState;
	}

	public void setDestinationState(StateInfoDTO destinationStateId) {
		this.destinationState = destinationStateId;
	}
	

	@Column(name = "SOURCE_PLACE", nullable = false)
	public String getSourcePlace() {
		return this.sourcePlace;
	}

	public void setSourcePlace(String sourcePlace) {
		this.sourcePlace = sourcePlace;
	}

	@Column(name = "SOURCE_ADDRESS", nullable = false)
	public String getSourceAddress() {
		return sourceAddress;
	}

	public void setSourceAddress(String sourceAddress) {
		this.sourceAddress = sourceAddress;
	}
	
	

	@Column(name = "DESTINATION_PLACE", nullable = false)
	public String getDestinationPlace() {
		return this.destinationPlace;
	}

	public void setDestinationPlace(String destinationPlace) {
		this.destinationPlace = destinationPlace;
	}

	@Column(name = "DESTINATION_ADDRESS", nullable = false)
	public String getDestinationAddress() {
		return destinationAddress;
	}

	public void setDestinationAddress(String destinationAddress) {
		this.destinationAddress = destinationAddress;
	}
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_REQUEST", length = 19)
	public Date getDateOfRequest() {
		return this.dateOfRequest;
	}

	public void setDateOfRequest(Date dateOfRequest) {
		this.dateOfRequest = dateOfRequest;
	}

	@Column(name = "TRUCK_TYPE", length = 45)
	public String getTruckType() {
		return this.truckType;
	}

	public void setTruckType(String truckType) {
		this.truckType = truckType;
	}

	@Column(name = "PARTIAL_LOAD_FLAG")
	public Boolean getPartialLoadFlag() {
		return this.partialLoadFlag;
	}

	public void setPartialLoadFlag(Boolean partialLoadFlag) {
		this.partialLoadFlag = partialLoadFlag;
	}

	@Column(name = "REMARKS")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "userBookingReqDTO")
	@JsonManagedReference
	public Set<TransComQuotesDTO> getTransComQuotesDTOs() {
		return this.transComQuotesDTOs;
	}

	public void setTransComQuotesDTOs(Set<TransComQuotesDTO> transComQuotesDTOs) {
		this.transComQuotesDTOs = transComQuotesDTOs;
	}

}
